version: "3.9"

services:
  db:
    image: postgres:14
    volumes:
    - /var/lib/thbattle/db:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    networks: [thb]
    restart: always

  backend:
    build:
      context: .
      target: backend
    volumes:
    - /var/lib/thbattle/backend:/settings
    environment:
      PYTHONPATH: /settings
      DJANGO_SETTINGS_MODULE: prod_settings
    depends_on: [db]
    networks: [thb]
    restart: always

  forest:
    build:
      context: .
      target: game
    ports:
    - "9999:9999"
    volumes:
    - /var/lib/thbattle/forest:/data/thb
    environment:
      INSTANCE: forest
      BACKEND_URL: 'http://${BACKEND_AUTH:-user:pass}@backend:8000/graphql'
      INTERCONNECT_URL: ''  # not yet used
    depends_on: [backend]
    networks: [thb]
    restart: always

  lake:
    build:
      context: .
      target: game
    ports:
    - "9998:9999"
    volumes:
    - /var/lib/thbattle/lake:/data/thb
    environment:
      INSTANCE: lake
      BACKEND_URL: 'http://${BACKEND_AUTH:-user:pass}@backend:8000/graphql'
      INTERCONNECT_URL: ''  # not yet used
    depends_on: [backend]
    networks: [thb]
    restart: always

  chat:
    build:
      context: .
      target: chat
    ports:
    - "7777:7777"
    environment:
      AYA_LOG: info
      BACKEND_URL: 'http://${BACKEND_AUTH:-user:pass}@backend:8000/graphql'
    depends_on: [backend]
    networks: [thb]
    restart: always

  nginx:
    build:
      context: .
      target: nginx
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/lib/thbattle/nginx:/usr/local/openresty/nginx/conf
    - /var/log/nginx:/var/log/nginx
    - nginx-certs:/var/lib/nginx-certs
    depends_on: [backend]
    networks: [thb]
    restart: always

networks:
  thb: {}
 

volumes:
  nginx-certs:
