[tool.poetry]
name = "thbattle"
version = "0.1.0"
description = "THBattle"
authors = ["Proton <feisuzhu@163.com>"]
license = "GPL-3.0+"

[tool.poetry.dependencies]
python = "^3.6"
gevent = "^20.5.0"
requests = "*"
raven = "*"
websocket-client = "*"
dnspython = "*"
msgpack = "^1.0.0"
mypy-extensions = "*"
typing-extensions = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
ipython = "*"
neovim = "*"
flake8 = "*"
coverage = "*"
mypy = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
