[tool.poetry]
name = "thbattle"
version = "0.1.0"
description = "THBattle"
authors = ["Proton <feisuzhu@163.com>"]
license = "GPL-3.0+"

[tool.poetry.dependencies]
python = "^3.10"
gevent = "^21.12.0"
requests = "^2.28.1"
raven = "^6.10.0"
websocket-client = "^1.3.3"
dnspython = "^2.2.1"
msgpack = "^1.0.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
ipython = "^8.4.0"
neovim = "^0.3.1"
flake8 = "^4.0.1"
coverage = "^6.4.1"
mypy = "^0.961"
jedi = "^0.18.1"
itsdangerous = "^2.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.masonry.api"
